# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autolabling_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_autolabling_settings(object):
    def setupUi(self, Dialog_autolabling_settings):
        Dialog_autolabling_settings.setObjectName("Dialog_autolabling_settings")
        Dialog_autolabling_settings.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_autolabling_settings)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog_autolabling_settings)
        self.doubleSpinBox.setMinimum(0.0)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setProperty("value", 0.6)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_autolabling_settings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_conf = QtWidgets.QLabel(Dialog_autolabling_settings)
        self.label_conf.setObjectName("label_conf")
        self.gridLayout.addWidget(self.label_conf, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_autolabling_settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Dialog_autolabling_settings)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 2)

        self.retranslateUi(Dialog_autolabling_settings)
        self.buttonBox.accepted.connect(Dialog_autolabling_settings.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_autolabling_settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_autolabling_settings)

    def retranslateUi(self, Dialog_autolabling_settings):
        _translate = QtCore.QCoreApplication.translate
        Dialog_autolabling_settings.setWindowTitle(_translate("Dialog_autolabling_settings", "Настройки авторазметки"))
        self.label.setText(_translate("Dialog_autolabling_settings", "Выберите классы, которые необходимо заменить/добавить:"))
        self.label_conf.setText(_translate("Dialog_autolabling_settings", "Порог уверенности:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_autolabling_settings = QtWidgets.QDialog()
    ui = Ui_Dialog_autolabling_settings()
    ui.setupUi(Dialog_autolabling_settings)
    Dialog_autolabling_settings.show()
    sys.exit(app.exec_())
