# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_class_yaml.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_new_class_yaml(object):
    def setupUi(self, Dialog_new_class_yaml):
        Dialog_new_class_yaml.setObjectName("Dialog_new_class_yaml")
        Dialog_new_class_yaml.resize(400, 115)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_new_class_yaml)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Dialog_new_class_yaml)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_new_class_yaml)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_new_class_yaml)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(Dialog_new_class_yaml)
        self.buttonBox.accepted.connect(Dialog_new_class_yaml.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_new_class_yaml.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_new_class_yaml)

    def retranslateUi(self, Dialog_new_class_yaml):
        _translate = QtCore.QCoreApplication.translate
        Dialog_new_class_yaml.setWindowTitle(_translate("Dialog_new_class_yaml", "Добавление класса"))
        self.label.setText(_translate("Dialog_new_class_yaml", "Введите название нового класса:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_new_class_yaml = QtWidgets.QDialog()
    ui = Ui_Dialog_new_class_yaml()
    ui.setupUi(Dialog_new_class_yaml)
    Dialog_new_class_yaml.show()
    sys.exit(app.exec_())
